version: "3.8"
services:
    nodeserver:
        build:
            context: ./backend
        ports:
            - 
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"